[versions]
kotlin = "2.0.21"
compose-multiplatform = "1.7.1"
koin = "3.5.3"
okhttp = "4.12.0"
jsoup = "1.17.2"
gson = "2.10.1"
snakeyaml = "2.2"
luaj = "3.0.1"
kotlinx-coroutines = "1.9.0"

[libraries]
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
luaj = { module = "org.luaj:luaj-jse", version.ref = "luaj" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
